### ISSUE TITLE
Need release to work on Python 3.10

### ISSUE THREAD

**Issue by zaneb** [testing-cabal/testtools#312] opened 2021-06-25 18:10 UTC
The latest release, 2.4.0, does not contain the change to remove unittest2 (#277). unittest2  cannot even be imported on Python 3.10, so all projects using testtools or anything that requires it (such as fixtures) cannot test on 3.10 until there is a new release of testtools.

**Comment by mtreinish** [comment] 2021-06-25 19:09
Closing as this a duplicate of #303 a new release is pending shortly. Please feel free to reopen if there is more to discuss on this though.

**Closed by mtreinish** 2021-06-25 19:09 UTC
